name: Add New Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  add-tests:
    name: Add new tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'DioxusLabs/Taffy'
          ref: 'refs/heads/main'
          path: 'taffy'
          sparse-checkout: |
            test_fixtures
          persist-credentials: false

      - uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'
          path: 'stretchable'
          fetch-depth: 0
          sparse-checkout: |
            tests/fixtures

      - run: |
          # Find most recent test branch
          $latest_branch = git branch -r | Where-Object { $_ -match 'origin/tests/add-tests-\d+\.\d+$' } | 
            ForEach-Object { $_.Trim() } | Sort-Object -Descending | Select-Object -First 1
          
          # Create new branch name
          $new_branch = "tests/add-tests-${{ github.run_number }}.${{ github.run_attempt }}"
          echo "new_branch=$new_branch" >> $env:GITHUB_OUTPUT
          
          if ($latest_branch) {
            # Checkout from the latest branch instead of main
            git checkout -b $new_branch ($latest_branch -replace 'origin/')
            Write-Host "Created new branch $new_branch from $latest_branch"
          } else {
            # If no previous branch exists, create from main
            git checkout -b $new_branch
            Write-Host "Created new branch $new_branch from main"
          }

          $files = 0
          $targetBasePath = "tests/fixtures"
          $stylesheet = get-item "./tests/fixtures/base_style.css"
          foreach ($item in Get-ChildItem -Path "../taffy/test_fixtures" -Recurse -Filter *.html)
          {
            if ($item.BaseName.StartsWith("x")) {
              continue;
            }
            
            $relPath = ($item | Resolve-Path -RelativeBasePath "../taffy/test_fixtures" -Relative).TrimStart("./")
            $targetPath = Join-Path $targetBasePath $relPath
            if (Test-Path $targetPath) {
              continue;
            }            

            # Process source file and write processed file at target path
            # - Remove <script> block
            # - Fix path to stylesheet
            $processed = @()
            $has_style = $false
            foreach($line in Get-Content $item) {
              if ($line -match '<script.*>.*<\/script>') {
                  continue
              }
          
              if ($line -match '<link.*>') {
                  if ($has_style) {
                      continue
                  }
                  $stylesheet_link = ($stylesheet | Resolve-Path -RelativeBasePath $targetPath.Directory -Relative)
                  $line = "  <link rel=""stylesheet"" type=""text/css"" href=""$stylesheet_link"">"
                  $has_style = $true
              }
          
              $processed += $line
            }            
            if ($has_style) {
                Out-File -FilePath $targetPath -InputObject $processed -encoding utf8
            }

            $files++;
          }

          if ($files -gt 0) {
            # Configure git
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions@users.noreply.github.com'

            # Commit files
            git add .
            git commit -m "test(layout): add $($files) new tests from Taffy repo"

            # Push to origin and create PR
            git push -u origin $($branch)
            gh pr create --head $($branch) --base refs/heads/main --title "Add $($files) new tests from Taffy" --body "Add $($files) new tests from Taffy" --reviewer mortencombat
          }

        shell: pwsh
        working-directory: 'stretchable'
        env:
          GH_TOKEN: ${{ github.token }}
