name: Add New Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Add new tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'stretchable'
          sparse-checkout: |
            tests/fixtures

      - uses: actions/checkout@v4
        with:
          repository: 'DioxusLabs/Taffy'
          ref: 'refs/heads/main'
          path: 'taffy'
          sparse-checkout: |
            test_fixtures

    # TODO: 
    # iterate over all files in taffy/test_fixtures
    # if file starts with x, skip it
    # if file already exists in stretchable/tests/fixtures, skip it
    # then copy the file to stretchable/tests/fixtures and modify it:
    #   - Remove <script> block
    #   - Fix path to stylesheet
    #   - Fix other potential errors such as >> or misspellings
    # commit the file
    #   'Add path/name test'
    #
    # if at least one file committed, create a new branch and create a PR into main
    #   'Add x new tests from Taffy'


