name: Add New Tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Add new tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            tests/fixtures

      - uses: actions/checkout@v4
        with:
          repository: 'DioxusLabs/Taffy'
          ref: 'refs/heads/main'
          path: 'taffy'
          sparse-checkout: |
            test_fixtures

      - run: |
          # Create branch
          $branch = "tests/add-tests-${{ github.run_attempt }}"
          git checkout -b $($branch)

          $files = 0
          $targetBasePath = "tests/fixtures"
          foreach ($item in Get-ChildItem -Path "taffy/test_fixtures" -Recurse -Filter *.html)
          {
            if ($item.BaseName.StartsWith("x")) {
              continue;
            }
            
            $relPath = ($item | Resolve-Path -RelativeBasePath "taffy/test_fixtures" -Relative).TrimStart("./")
            $targetPath = Join-Path $targetBasePath $relPath
            if (Test-Path $targetPath) {
              continue;
            }            

            Write-Host $item
            Write-Host $targetPath

            Copy-Item -Path $item.FullName -Destination $targetPath -Force -Confirm:$false

            # TODO: Process file
            # - Remove <script> block
            # - Fix path to stylesheet
            # - Fix other potential errors such as >> or misspellings

            # Commit file
            # $relTargetPath = Join-Path tests/fixtures $relPath
            # git add $($relTargetPath)
            # git commit -m "test(layout): add $($item.BaseName)"
            $files++;
          }

          if ($files -gt 0) {
            # Configure git
            git config --global user.name 'Kenneth Trelborg Vestergaard'
            git config --global user.email 'mortencombat@users.noreply.github.com'

            # Commit files
            git add .
            git commit -m "test(layout): add new tests from Taffy repo"

            # Push to origin and create PR
            git push -u origin $($branch)
            gh pr create --head $($branch) --base refs/heads/main --title 'Add $($files) new tests from Taffy' --reviewer mortencombat
          }

        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
